export const MemberModel = {
  memberId: null,
  address: null,
  balance: null,
  createDate: null,
  description: null,
  email: null,
  password: null,
  phone: null,
  point: null,
  sex: null,
  state: null,
  modifyDate: null,
  username: null,
  remark: null,
};